"""
db/seed_synthetic_data.py

Generates and inserts a small synthetic dataset for local testing and
demonstration. All names, emails, and organizations are fake, generated by
Faker with a fixed seed for reproducibility. No real institutional or
personal data is used or referenced anywhere in this script.

Scale (small set, intended for exercising every function in db/queries.py,
not for load testing):
    3 organizations
    10 supervisors
    40 interns
    2 pay periods, with simulated sent/reply/tracking history for both

Usage:
    export DATABASE_URL="postgresql://...">
    python3 -m db.seed_synthetic_data
"""

import random
from datetime import date, datetime, timedelta

from faker import Faker

from db.models import get_session_factory, Organization, Supervisor, Intern
from db.queries import (
    get_or_create_pay_period,
    log_sent_email,
    log_supervisor_reply,
    upsert_submission_tracking,
)

SEED = 42
fake = Faker()
Faker.seed(SEED)
random.seed(SEED)

N_ORGANIZATIONS = 3
N_SUPERVISORS = 10
N_INTERNS = 40

# Fake, clearly-synthetic domains. Not real institutional or company domains.
EMPLOYEE_DOMAIN = "example.org"
STUDENT_DOMAIN = "student.example.edu"


def build_organizations(session) -> list[Organization]:
    orgs = []
    for _ in range(N_ORGANIZATIONS):
        org = Organization(name=fake.company())
        session.add(org)
        orgs.append(org)
    session.flush()
    return orgs


def build_supervisors(session, orgs: list[Organization]) -> list[Supervisor]:
    supervisors = []
    for _ in range(N_SUPERVISORS):
        first = fake.first_name()
        last = fake.last_name()
        sup = Supervisor(
            first_name=first,
            last_name=last,
            email=f"{first.lower()}.{last.lower()}@{EMPLOYEE_DOMAIN}",
            organization=random.choice(orgs),
        )
        session.add(sup)
        supervisors.append(sup)
    session.flush()
    return supervisors


def build_interns(session, supervisors: list[Supervisor]) -> list[Intern]:
    interns = []
    for _ in range(N_INTERNS):
        first = fake.first_name()
        last = fake.last_name()
        supervisor = random.choice(supervisors)
        intern = Intern(
            first_name=first,
            last_name=last,
            email=f"{first.lower()}.{last.lower()}@{EMPLOYEE_DOMAIN}",
            student_email=f"{first.lower()}{last.lower()}@{STUDENT_DOMAIN}",
            supervisor=supervisor,
            organization=supervisor.organization,
            start_date=fake.date_between(start_date="-1y", end_date="today"),
        )
        session.add(intern)
        interns.append(intern)
    session.flush()
    return interns


def build_pay_periods(session):
    """Two consecutive semi-monthly pay periods."""
    periods = []
    p1 = get_or_create_pay_period(
        session,
        label="Jun 16-30 2026",
        start_date=date(2026, 6, 16),
        end_date=date(2026, 6, 30),
        submission_deadline=date(2026, 6, 30),
        payroll_deadline=date(2026, 7, 2),
    )
    p2 = get_or_create_pay_period(
        session,
        label="Jul 1-15 2026",
        start_date=date(2026, 7, 1),
        end_date=date(2026, 7, 15),
        submission_deadline=date(2026, 7, 15),
        payroll_deadline=date(2026, 7, 17),
    )
    periods.extend([p1, p2])
    session.flush()
    return periods


def simulate_period(session, period, interns: list[Intern]):
    """
    For each intern, simulate: most submit, a few don't (MISSING), most
    submitted timesheets get a reply, most replies are APPROVED, a few are
    REJECTED or CORRECTIONS, a few submissions are left PENDING (no reply yet).
    """
    for intern in interns:
        roll = random.random()

        if roll < 0.05:
            # Did not submit at all this period.
            upsert_submission_tracking(
                session,
                pay_period_id=period.id,
                intern_id=intern.id,
                status="MISSING",
            )
            continue

        sent_at = datetime.combine(
            period.start_date, datetime.min.time()
        ) + timedelta(days=random.randint(0, (period.end_date - period.start_date).days))

        sent = log_sent_email(
            session,
            intern_id=intern.id,
            supervisor_id=intern.supervisor_id,
            pay_period_id=period.id,
            sent_at=sent_at,
            email_subject=f"Timesheet Approval Request for {intern.first_name} {intern.last_name}",
            hours_reported=round(random.uniform(10, 20), 2),
            submission_date=sent_at.date(),
        )

        reply_roll = random.random()
        if reply_roll < 0.10:
            # Submitted, no reply yet this period.
            upsert_submission_tracking(
                session,
                pay_period_id=period.id,
                intern_id=intern.id,
                submitted_at=sent_at,
                status="PENDING",
            )
            continue

        response_type = random.choices(
            ["APPROVED", "REJECTED", "CORRECTIONS"], weights=[85, 8, 7]
        )[0]
        received_at = sent_at + timedelta(hours=random.randint(1, 48))

        log_supervisor_reply(
            session,
            sent_log_id=sent.id,
            intern_id=intern.id,
            supervisor_id=intern.supervisor_id,
            pay_period_id=period.id,
            received_at=received_at,
            response_type=response_type,
            match_method="sent_log_fk",
        )

        upsert_submission_tracking(
            session,
            pay_period_id=period.id,
            intern_id=intern.id,
            submitted_at=sent_at,
            approved_at=received_at if response_type == "APPROVED" else None,
            status=response_type,
        )


def main():
    Session = get_session_factory()
    session = Session()

    orgs = build_organizations(session)
    supervisors = build_supervisors(session, orgs)
    interns = build_interns(session, supervisors)
    periods = build_pay_periods(session)

    for period in periods:
        simulate_period(session, period, interns)

    session.commit()

    print(f"Seeded {len(orgs)} organizations, {len(supervisors)} supervisors, "
          f"{len(interns)} interns, {len(periods)} pay periods.")


if __name__ == "__main__":
    main()
